version: '2.1'

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'geldstroom'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
        test: "/usr/bin/mysql --user=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    ports:
        - '3306:3306'  
    volumes:
        - ./data:/var/lib/mysql   
    
