version: '2.1'

services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - VIRTUAL_HOST=geldstroom.cotcapp.my.id,www.geldstroom.cotcapp.my.id
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=geldstroom.cotcapp.my.id
      - LETSENCRYPT_EMAIL=a.novaladip@yahoo.com 
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'geldstroom'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
        test: "/usr/bin/mysql --user=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    ports:
        - '3306:3306'  
    volumes:
        - ./data:/var/lib/mysql   
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen